# Generated by Django 2.0.13 on 2019-07-30 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=100)),
                ('boolean_answer', models.PositiveIntegerField(default=0)),
                ('boolean_num', models.PositiveIntegerField(default=0)),
                ('boolean_ratio', models.FloatField(default=0)),
                ('short_answer', models.PositiveIntegerField(default=0)),
                ('short_num', models.PositiveIntegerField(default=0)),
                ('short_ratio', models.FloatField(default=0)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
